# TCL File Generated by Component Editor 8.1
# Wed Jun 03 13:26:20 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sb16_avalon_wrapper "sb16_avalon_wrapper" v1.0
# | null 2009.06.03.13:26:20
# | 
# | 
# | E:/markm/pace/pacedev.net/sw/src/platform/zet/tb/sb16_avalon_wrapper.vhd
# | 
# |    ./sb16_avalon_wrapper.vhd syn, sim
# |    ./E:/markm/pace/pacedev.net/sw/src/platform/zet/sb16.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module sb16_avalon_wrapper
# | 
set_module_property DESCRIPTION ""
set_module_property NAME sb16_avalon_wrapper
set_module_property VERSION 1.0
set_module_property GROUP PACE
set_module_property DISPLAY_NAME sb16_avalon_wrapper
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE sb16_avalon_wrapper.vhd
set_module_property TOP_LEVEL_HDL_MODULE sb16_avalon_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sb16_avalon_wrapper.vhd {SYNTHESIS SIMULATION}
add_file E:/markm/pace/pacedev.net/sw/src/platform/zet/sb16.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end
set_interface_property clockreset ptfSchematicName ""

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressSpan 128
set_interface_property s1 bridgesToMaster ""
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 minimumUninterruptedRunLength 1
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clockreset

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 5
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq0
# | 
add_interface irq0 interrupt end
set_interface_property irq0 associatedAddressablePoint s1

set_interface_property irq0 ASSOCIATED_CLOCK clockreset

add_interface_port irq0 ins_irq0_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_0
# | 
add_interface conduit_end_0 conduit end

set_interface_property conduit_end_0 ASSOCIATED_CLOCK clockreset

add_interface_port conduit_end_0 coe_audio_l export Output 16
add_interface_port conduit_end_0 coe_audio_r export Output 16
# | 
# +-----------------------------------
