# TCL File Generated by Component Editor 8.1
# Tue Sep 22 16:13:15 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_slave_conduit "avalon_slave_conduit" v1.0
# |  2009.09.22.16:13:15
# | Generic avalon slave conduit
# | 
# | D:/work/S5A/sw/S5A-sw-MFP/src/avalon_slave_conduit/avalon_slave_conduit.vhd
# | 
# |    ./avalon_slave_conduit.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module avalon_slave_conduit
# | 
set_module_property DESCRIPTION "Generic avalon slave conduit"
set_module_property NAME avalon_slave_conduit
set_module_property VERSION 1.0
set_module_property GROUP S5A
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_slave_conduit
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_unsigned.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE avalon_slave_conduit.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalon_slave_conduit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon_slave_conduit.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter WIDTH_AD NATURAL 10
set_parameter_property WIDTH_AD DISPLAY_NAME WIDTH_AD
set_parameter_property WIDTH_AD UNITS None
set_parameter_property WIDTH_AD AFFECTS_PORT_WIDTHS true
add_parameter WIDTH NATURAL 8
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end
set_interface_property clockreset ptfSchematicName ""

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 bridgesToMaster ""
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 minimumUninterruptedRunLength 1
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clockreset

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input -1
add_interface_port s1 avs_s1_readdata readdata Output -1
add_interface_port s1 avs_s1_writedata writedata Input -1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_0
# | 
add_interface conduit_end_0 conduit end

set_interface_property conduit_end_0 ASSOCIATED_CLOCK clockreset

add_interface_port conduit_end_0 coe_s2_chipselect export Output 1
add_interface_port conduit_end_0 coe_s2_address export Output -1
add_interface_port conduit_end_0 coe_s2_readdata export Input -1
add_interface_port conduit_end_0 coe_s2_writedata export Output -1
add_interface_port conduit_end_0 coe_s2_read export Output 1
add_interface_port conduit_end_0 coe_s2_write export Output 1
add_interface_port conduit_end_0 coe_s2_waitrequest export Input 1
add_interface_port conduit_end_0 coe_s2_clk export Output 1
add_interface_port conduit_end_0 coe_s2_reset export Output 1
# | 
# +-----------------------------------
