typedef struct zeropage_t
{
  uint8_t   current_col;
  uint8_t   current_row;
  int8_t   	x_offset_within_tile;
  int8_t   	y_offset_within_tile;
  uint8_t   sprite_index;
  uint8_t   dir;
  uint8_t   lsb_row_level_data_addr;
  uint8_t   msb_row_level_data_addr;
  uint8_t   byte_8;
  uint8_t   byte_9;
  uint8_t   word_a;
  uint8_t   lsb_line_addr_pg1;
  uint8_t   msb_line_addr_pg1;
  uint8_t   lsb_line_addr_pg2;
  uint8_t   msb_line_addr_pg2;
  uint8_t   msg_addr;
  uint8_t   curr_guard_col;
  uint8_t   curr_guard_row;
  uint8_t   curr_guard_sprite;
  int8_t    curr_guard_dir;
  int8_t    curr_guard_state;
  int8_t   	curr_guard_x_offset;
  int8_t   	curr_guard_y_offset;
  uint8_t   curr_guard;
  uint8_t   nibble_cnt;
  uint8_t   scanline;
  uint8_t   col_addr_offset;
  uint8_t   scanline_cnt;
  uint8_t   msg_char;
  uint8_t   hires_page_msb_1;
  uint8_t   lchar_mask;
  uint8_t   rchar_mask;
  uint8_t   collision_detect;
  uint8_t   guard_respawn_col;
  uint8_t   sndq_length;
  uint8_t   guard_ai_col;
  uint8_t   guard_ai_row;
  uint8_t   target_col;
  uint8_t   guard_ai_dir;
  uint8_t   guard_ai_best_delta;
  uint8_t   farthest_left;
  uint8_t   farthest_right;
  uint8_t   farthest_updown_plyr_row;
  uint8_t   byte_5d;
  uint8_t   byte_5e;
  uint8_t   guard_trap_cnt_init;
  uint8_t   byte_60[3];
  uint8_t   byte_63;
  uint8_t   byte_64;
  uint8_t   byte_69;
  uint8_t   byte_6d;
  uint8_t   col_pixel_shift;
  uint8_t   drawing;
  uint8_t   r;
  uint8_t   y0;
  uint8_t   x0;
  uint8_t   x;
  uint8_t   y;
  uint8_t   re;
  uint8_t   minus_x;
  uint8_t   minus_y;
  uint8_t   circle_mask;
  uint8_t   col;
  uint8_t   row;
  uint8_t   display_char_page;
  uint8_t   byte_88;
  uint8_t   hundreds;
  uint8_t   tens;
  uint8_t   units;
  uint8_t   game_speed;
  uint8_t   no_guards;
  uint32_t  score;
  uint8_t   packed_byte_cnt;
  uint8_t   no_gold;
  uint8_t   enable_collision_detect;
  uint8_t   paddles_detected;
  uint8_t   level_0_based;
  uint8_t   unused_97;
  uint8_t   no_lives;
  uint8_t   sound_enabled;
  uint8_t   level_active;
  uint8_t   not_falling;
  int8_t   	dig_dir;
  uint8_t   no_cheat;
  uint8_t   key_1;
  uint8_t   key_2;
  uint8_t   dig_sprite;
  uint8_t   timer;
  uint8_t   editor_n;
  uint8_t   no_eos_ladder_tiles;
  uint8_t   falling_snd_freq;
  uint8_t   wipe_next_time;
  uint8_t   level;
  uint8_t   attract_mode;
  uint8_t		*demo_inp_ptr;
  uint8_t   demo_inp_key_1_2;
  uint8_t   demo_inp_cnt;
  uint8_t   byte_ac;
  uint8_t   game_over_loop_cnt;
  uint8_t   no_eos_ladder_entries;
  uint8_t   initial_cnt;
  uint8_t   blink_char;
  uint8_t   sound_cnt;
  uint8_t   sound_bits;
  uint8_t   sound_setting;
  uint8_t   debug_page;
  uint8_t   zp_de;
  uint8_t   char_render_buf;
  
} ZEROPAGE, *PZEROPAGE;

typedef struct hs_entry_t
{
	uint8_t		initial[3];
	uint8_t		level;
	uint32_t	score;
	
} HS_ENTRY, *PHS_ENTRY;

#define MAX_HOLES         0x1e
#define MAX_GUARDS        5
#define MAX_EOS_LADDERS   0x4d
