-- megafunction wizard: %Altera PLL v14.1%
-- GENERATION: XML
-- pll5_50.vhd

-- Generated using ACDS version 14.1 190 at 2015.04.04.17:54:14

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pll5_50 is
	generic (
		REF_CLK  : in string  := "50.0 MHz";
		NUM_CLKS : in integer := 4;
		CLK0 	 : in string  := "20.000000 MHz";
		CLK1 	 : in string  := "40.000000 MHz";
		CLK2 	 : in string  := "18.421052 MHz";
		CLK3 	 : in string  := "10.000000 MHz"
		);
	port (
		refclk   : in  std_logic := '0'; --  refclk.clk
		rst      : in  std_logic := '0'; --   reset.reset
		outclk_0 : out std_logic;        -- outclk0.clk
		outclk_1 : out std_logic;        -- outclk1.clk
		outclk_2 : out std_logic;        -- outclk2.clk
		outclk_3 : out std_logic         -- outclk3.clk
	);
end entity pll5_50;

architecture rtl of pll5_50 is
	component pll5_50_0002 is
		generic (
			REF_CLK  : in string;
			NUM_CLKS : in integer;
			CLK0 	 : in string;
			CLK1 	 : in string;
			CLK2 	 : in string;
			CLK3 	 : in string
		);
		port (
			refclk   : in  std_logic := 'X'; -- clk
			rst      : in  std_logic := 'X'; -- reset
			outclk_0 : out std_logic;        -- clk
			outclk_1 : out std_logic;        -- clk
			outclk_2 : out std_logic;        -- clk
			outclk_3 : out std_logic;        -- clk
			locked   : out std_logic         -- export
		);
	end component pll5_50_0002;

begin

	pll5_50_inst : component pll5_50_0002
		generic map(
			REF_CLK  => REF_CLK,
			NUM_CLKS => NUM_CLKS,
			CLK0 	 => CLK0,
			CLK1 	 => CLK1,
			CLK2 	 => CLK2,
			CLK3 	 => CLK3
		)
		port map (
			refclk   => refclk,   --  refclk.clk
			rst      => rst,      --   reset.reset
			outclk_0 => outclk_0, -- outclk0.clk
			outclk_1 => outclk_1, -- outclk1.clk
			outclk_2 => outclk_2, -- outclk2.clk
			outclk_3 => outclk_3, -- outclk3.clk
			locked   => open      -- (terminated)
		);

end architecture rtl; -- of pll5_50

