 
 
;
; ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
; º     This file is generated by The Interactive Disassembler (IDA)        º
; º                      Licensed to: Unknown User ;-)                      º
; º     Copyright (c) 1999 by DataRescue sa/nv, <ida@datarescue.com>        º
; ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
;

; Processor:        z80
; Target assembler: ASxxxx by Alan R. Baldwin v1.5
       .area   idaseg (ABS)
       .hd64 ; this is needed only for HD64180

; ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ

; Segment type: Regular
; segment 'video'
        .org 0x3C00
video_ram:.ds 0x400                     ; DATA XREF: update_bullet+84o
                                        ; update_bullet+91o ...
; end of 'video'

; ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ

; Segment type: Regular
; segment 'ram'
        .org 0x4300
fire_throttle:.ds 1                     ; DATA XREF: handle_fire+5r
                                        ; handle_fire+Cw ...
invaders_left:.ds 1                     ; DATA XREF: update_bullet+62r
                                        ; update_bullet+69w ...
row_1_invader_addr:.ds 2                ; DATA XREF: animate_invaders+2r
                                        ; find_end_of_lowest_invader_row+15r ...
row_2_invader_addr:.ds 2                ; DATA XREF: animate_invaders+13r
                                        ; find_end_of_lowest_invader_row+Er ...
row_3_invader_addr:.ds 2                ; DATA XREF: animate_invaders+19r
                                        ; find_end_of_lowest_invader_row+7r ...
row_4_invader_addr:.ds 2                ; DATA XREF: animate_invaders+1Fr
                                        ; find_end_of_lowest_invader_rowr ...
invader_dir:.ds 1                       ; DATA XREF: code:49DCw
                                        ; animate_and_move_invaders+3r ...
ufo_TTL:.ds 1                           ; DATA XREF: check_and_start_ufo+16w
                                        ; update_ufo+35r ...
ufo_timer:.ds 1                         ; DATA XREF: update_bullet+C9w
                                        ; check_and_start_ufor ...
ufo_dir:.ds 1                           ; DATA XREF: handle_fire+15r
                                        ; handle_fire+1Aw ...
                                        ; something with UFO (direction?)
wave_no:.ds 1                           ; DATA XREF: code:49CFw code:49FCr ...
no_lives:.ds 1                          ; DATA XREF: update_score_and_chk_bonus_life+1Dr
                                        ; update_score_and_chk_bonus_life+21w ...
; end of 'ram'

; File Name   : tandy.bin
; Format      : Binary File
; Base Address: 0000h Range: 4310h - 5000h Loaded length: 0CF0h
; ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ

; Segment type: Pure code
; segment 'code'
        .org 0x4310
ufo_active:.db 0                        ; DATA XREF: handle_fire+Fr
                                        ; update_bullet+C6w ...
bullet_active:.db 0                     ; DATA XREF: handle_firer
                                        ; handle_fire+1Fw ...
unused_4312:.db 0xC9                    ; DATA XREF: code:49C9w code:4AC1w ...
base_centre:.dw 0x45B0                  ; DATA XREF: handle_fire+23r
                                        ; check_and_handle_move+17r ...
unused_4315:.db 1                       ; DATA XREF: code:49C6w
init_row_1_invader_addr:.dw video_ram+0x40 ; DATA XREF: code:4A1Eo
init_row_2_invader_addr:.dw video_ram+0xC0
init_row_3_invader_addr:.dw video_ram+0x140
init_row_4_invader_addr:.dw video_ram+0x1C0
bullet_addr:.dw video_ram+0x253         ; DATA XREF: handle_fire+2Aw
                                        ; update_bullet+1r ...
game_timer:.db 0x60                     ; DATA XREF: code:4F02w code:4F26r ...
invader_timer:.db 0x2B                  ; DATA XREF: code:4A98w code:4F6Cr ...
keybd_state:.db 0                       ; DATA XREF: code:49D8w code:4F17r ...
invader_30pt:.db 0xA0, 0xB6, 0xBF, 0xB9, 0x90, 0x1A, 1, 0x20, 0x86, 0x20, 0x89
                                        ; DATA XREF: code:4570o code:4A72o
        .db 0x20, 0
invader_20pt:.db 0x9C, 0xB7, 0xBF, 0xBB, 0xAC, 0x1A, 1, 0x8C, 0x83, 0x20, 0x83
                                        ; DATA XREF: code:457Co code:4A7Bo
        .db 0x8C, 0
invader_10pt:.db 0xBE, 0xBB, 0xBF, 0xB7, 0xBD, 0x1A, 1, 0x8C, 0x83, 0x20, 0x83
                                        ; DATA XREF: code:4588o code:4A84o
        .db 0x8C, 0
ufo:    .db 0x8C, 0xB7, 0xB7, 0xB7, 0xB7, 0x8C, 0 ; DATA XREF: code:4594o
                                        ; check_and_start_ufo+2Ao
shield: .db 0xB8, 0xBF, 0xBF, 0xBF, 0xBF, 0xBF, 0xB4, 0x1A, 8, 8, 1, 0x8F
                                        ; DATA XREF: code:4A4Bo
        .db 0x8F, 0x83, 0x83, 0x83, 0x8F, 0x8F, 0
player: .db 0xB8, 0xBC, 0xBF, 0xBC, 0xB4, 0 ; DATA XREF: code:4AA1o
explosion:.db 0x82, 0x84, 0x20, 0x88, 0x81, 0x1A, 1, 0x88, 0x81, 0x20, 0x82
                                        ; DATA XREF: update_bullet+53o
        .db 0x84, 0
        .db    0 ;  
        .db    0 ;  
blank_space:.db 0x1B, 1, 0x20, 0x20, 0x20, 0x20, 0x20, 0x1A, 1, 0x20, 0x20
                                        ; DATA XREF: update_bullet+5Co
        .db 0x20, 0x20, 0x20, 0
aPlay:  .ascii 'PLAY'                   ; DATA XREF: code:4564o
        .db 9, 0xD6, 0x3C
aTandyInvaders:.ascii 'TANDY       INVADERS'
        .db 9, 0x54, 0x3D
aScoreAdvanceTa:.ascii '* SCORE ADVANCE TABLE *'
        .db 0
aTandyElectroni:.ascii '* TANDY ELECTRONICS *' ; DATA XREF: code:4558o
                                        ; code:45BBo
        .db 0
a30Points:.ascii '<----   30  POINTS'   ; DATA XREF: code:45A0o
        .db 9, 0x1E, 0x3E
a20Points:.ascii '<----   20  POINTS'
        .db 9, 0x9E, 0x3E
a10Points:.ascii '<----   10  POINTS'
        .db 9, 0x1E, 0x3F
a_Mystery:.ascii '<----   ?   MYSTERY'
        .db 0
aPressZKeyToMov:.ascii 'PRESS "Z" KEY TO MOVE LEFT' ; DATA XREF: code:45C7o
        .db 9, 0x13, 0x3D
aPressXKeyToMov:.ascii 'PRESS "X" KEY TO MOVE RIGHT'
        .db 9, 0x93, 0x3D
aPressKeyToFire:.ascii 'PRESS " " KEY TO FIRE !'
        .db 9, 0x13, 0x3E
aPressRKeyToSta:.ascii 'PRESS "R" KEY TO START'
        .db 0
aGAMEOVER:.ascii 'G A M E - O V E R'    ; DATA XREF: code:494Bo
        .db 0
aScore00000High:.ascii '  SCORE  00000                                 HIGH-SCOR'
                                        ; DATA XREF: code:4544o
        .ascii 'E 00000'
        .db 0

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


display_message:                        ; CODE XREF: code:4547p code:455Bp ...
        push    bc

loc_0_44E6:                             ; CODE XREF: display_message+15j
        ld      a, (hl)                 ; get character
        or      a                       ; finished?
        jr      Z, loc_0_4503           ; yes, exit
        cp      #1
        jr      NZ, loc_0_44FC
        ld      b, #5                   ; 5 characters to print
        ld      a, #8                   ; backspace

loc_0_44F2:                             ; CODE XREF: display_message+12j
        push    de
        call    0x33                    ; display character
        pop     de
        djnz    loc_0_44F2              ; loop

loc_0_44F9:                             ; CODE XREF: display_message+1Cj
        inc     hl                      ; next character
        jr      loc_0_44E6              ; loop
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_44FC:                             ; CODE XREF: display_message+7j
        push    de
        call    0x33                    ; display character
        pop     de
        jr      loc_0_44F9              ; loop
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4503:                             ; CODE XREF: display_message+3j
        pop     bc
        ret     
; End of function display_message


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


display_message_slowly:                 ; CODE XREF: display_message_slowly+11j
                                        ; code:494Ep
        ld      a, (hl)                 ; get character
        or      a                       ; done?
        ret     Z                       ; yes, exit
        push    de
        push    bc
        call    0x33                    ; display character
        ld      bc, #8960               ; ~130ms
        call    0x60                    ; delay
        pop     bc
        pop     de
        inc     hl                      ; next character
        jr      display_message_slowly  ; loop through message
; End of function display_message_slowly


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


wipe_screen_left_to_right_slow:         ; CODE XREF: code:454Fp code:45AFp ...
        exx     
        ld      hl, #0x3BFF             ; start of video (-1)
        ld      b, #0x40 ; '@'          ; characters/line

loc_0_451E:                             ; CODE XREF: wipe_screen_left_to_right_slow+19j
        push    bc
        inc     hl                      ; next column
        push    hl
        ld      b, #0xF                 ; 15 lines
        ld      a, #0x20 ; ' '          ; space
        ld      de, #0x40 ; '@'         ; next line address

loc_0_4528:                             ; CODE XREF: wipe_screen_left_to_right_slow+12j
        ld      (hl), a                 ; display character
        add     hl, de                  ; next line
        djnz    loc_0_4528              ; loop all lines
        call    delay_1_5ms
        pop     hl
        pop     bc
        djnz    loc_0_451E              ; loop all columns
        exx     
        ret     
; End of function wipe_screen_left_to_right_slow

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

START:
        di      
        ld      a, #0xF
        call    0x33                    ; display character
        ld      sp, #0x428A
        ld      hl, #video_ram+0x3C0    ; cursor position
        ld      (0x4020), hl
        ld      hl, #aScore00000High    ; "  SCORE  00000                         "...
        call    display_message
        ld      a, #0x20 ; ' '
        ld      (video_ram+0x3FF), a

attract_loop:                           ; CODE XREF: code:45D6j code:4960j
        call    wipe_screen_left_to_right_slow
        ld      hl, #video_ram+0x394    ; cursor position
        ld      (0x4020), hl
        ld      hl, #aTandyElectroni    ; "* TANDY ELECTRONICS *"
        call    display_message
        ld      hl, #video_ram+0x9E     ; cursor position
        ld      (0x4020), hl
        ld      hl, #aPlay              ; "PLAY"
        call    print_slow_and_check_for_R_key
        ld      hl, #video_ram+0x192    ; cursor position
        ld      (0x4020), hl
        ld      hl, #invader_30pt
        call    display_message
        ld      hl, #video_ram+0x212    ; cursor position
        ld      (0x4020), hl
        ld      hl, #invader_20pt
        call    display_message
        ld      hl, #video_ram+0x292    ; cursor poition
        ld      (0x4020), hl
        ld      hl, #invader_10pt
        call    display_message
        ld      hl, #video_ram+0x312    ; cursor position
        ld      (0x4020), hl
        ld      hl, #ufo
        call    display_message
        ld      hl, #video_ram+0x19E    ; cursor position
        ld      (0x4020), hl
        ld      hl, #a30Points          ; "<----   30  POINTS"
        call    print_slow_and_check_for_R_key
        ld      bc, #0xFFFF             ; ~1s
        call    0x60                    ; delay
        call    0x60                    ; delay

loc_0_45AF:
        call    wipe_screen_left_to_right_slow
        call    check_for_R_key
        ld      hl, #video_ram+0x394
        ld      (0x4020), hl
        ld      hl, #aTandyElectroni    ; "* TANDY ELECTRONICS *"
        call    display_message
        ld      hl, #video_ram+0x93
        ld      (0x4020), hl
        ld      hl, #aPressZKeyToMov    ; "PRESS \"Z\" KEY TO MOVE LEFT"
        call    print_slow_and_check_for_R_key
        ld      bc, #65535              ; ~1s
        call    0x60                    ; delay
        call    0x60                    ; delay
        jp      attract_loop

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


check_for_R_key:                        ; CODE XREF: code:45B2p
                                        ; print_slow_and_check_for_R_key+23p
        ld      a, (0x3804)             ; read keyboard
        cp      #4                      ; "R"?
        jp      Z, start_game           ; yes, skip
        ret     
; End of function check_for_R_key


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


compare_video_addresses:                ; CODE XREF: update_bullet+26p
                                        ; update_bullet+36p ...
        push    hl                      ; bullet address
        push    de                      ; video address to check
        ld      a, h
        cp      d                       ; same MSB?
        jr      Z, loc_0_45EE           ; yes, continue
        jr      NC, loc_0_45F4          ; continue if bullet below

no_hit:                                 ; CODE XREF: compare_video_addresses+10j
        xor     a                       ; flag no hit

loc_0_45EB:                             ; CODE XREF: compare_video_addresses+14j
                                        ; compare_video_addresses+18j
        pop     de
        pop     hl
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_45EE:                             ; CODE XREF: compare_video_addresses+4j
        ld      a, l
        cp      e                       ; same address?
        jr      Z, loc_0_45F8           ; yes, continue
        jr      C, no_hit               ; exit if bullet above

loc_0_45F4:                             ; CODE XREF: compare_video_addresses+6j
        ld      a, #0xFF                ; flag bullet right/below
        jr      loc_0_45EB
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_45F8:                             ; CODE XREF: compare_video_addresses+Ej
        ld      a, #0x20 ; ' '          ; flag bullet match
        jr      loc_0_45EB
; End of function compare_video_addresses


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


animate_invaders:                       ; CODE XREF: animate_and_move_invaders+2Bp
                                        ; code:4B91p
        push    hl
        push    bc
        ld      hl, (row_1_invader_addr)
        ld      b, #0x3F ; '?'          ; characters/line-1

animate_top_row:                        ; CODE XREF: animate_invaders+10j
        ld      a, (hl)                 ; get character from video
        bit     7, a                    ; graphic character?
        jr      Z, loc_0_460B           ; no, skip
        xor     #0xF                    ; invert top 4 pixels
        ld      (hl), a                 ; display

loc_0_460B:                             ; CODE XREF: animate_invaders+Aj
        inc     hl                      ; next video address
        djnz    animate_top_row         ; loop thru line
        push    de
        ld      hl, (row_2_invader_addr)
        call    animate_invader_row
        ld      hl, (row_3_invader_addr)
        call    animate_invader_row
        ld      hl, (row_4_invader_addr)
        call    animate_invader_row
        pop     de
        pop     bc
        pop     hl
        ret     
; End of function animate_invaders


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


animate_invader_row:                    ; CODE XREF: animate_invaders+16p
                                        ; animate_invaders+1Cp ...
        push    hl                      ; invader row addr
        ld      b, #0x40 ; '@'          ; characters/line

loc_0_4628:                             ; CODE XREF: animate_invader_row+15j
        ld      a, (hl)                 ; get character from video
        cp      #0x8C ; 'Œ'
        jr      Z, loc_0_4636
        cp      #0x83 ; 'ƒ'
        jr      NZ, loc_0_4639          ; not part of animation, skip
        ld      a, #0x8C ; 'Œ'          ; 0x83->0x8C
        ld      (hl), a                 ; display
        jr      loc_0_4639
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4636:                             ; CODE XREF: animate_invader_row+6j
        ld      a, #0x83 ; 'ƒ'          ; 0x8C->0x83
        ld      (hl), a                 ; display

loc_0_4639:                             ; CODE XREF: animate_invader_row+Aj
                                        ; animate_invader_row+Fj
        inc     hl                      ; next video address
        djnz    loc_0_4628              ; loop thru line
        pop     hl
        ret     
; End of function animate_invader_row


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


move_video_line_right_HL:               ; CODE XREF: check_and_handle_move+14p
                                        ; update_ufo+2Ap ...
        push    hl
        ld      de, #0x3E ; '>'         ; start at right end
        add     hl, de
        push    hl
        pop     de
        inc     de                      ; DE = end of row
        ld      b, #63                  ; number of characters/line-1
        ld      a, (de)                 ; get character from end of row
        bit     7, a                    ; graphic?
        jr      Z, loc_0_4650           ; no, skip
        ld      a, #0x20 ; ' '          ; space
        ld      (de), a                 ; display space

loc_0_4650:                             ; CODE XREF: move_video_line_right_HL+Dj
                                        ; move_video_line_right_HL+1Cj
        bit     7, (hl)                 ; graphic character left byte?
        jr      Z, loc_0_4658           ; no, skip
        ld      a, (hl)                 ; get character left byte
        ld      (de), a                 ; display to the right
        ld      (hl), #0x20 ; ' '       ; display space at left-hand byte

loc_0_4658:                             ; CODE XREF: move_video_line_right_HL+14j
        dec     hl
        dec     de
        djnz    loc_0_4650              ; loop through line
        pop     hl
        ld      (hl), #0x20 ; ' '       ; display space
        ret     
; End of function move_video_line_right_HL


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


move_video_line_left_HL:                ; CODE XREF: check_and_handle_move+2Bp
                                        ; update_ufo+32p ...
        push    hl
        push    hl
        pop     de
        inc     hl
        ld      b, #63                  ; characters/line-1
        ld      a, (de)                 ; get character LH byte
        bit     7, a                    ; graphic?
        jr      Z, loc_0_466E           ; no, skip
        ld      a, #0x20 ; ' '          ; space
        ld      (de), a                 ; display space LH byte

loc_0_466E:                             ; CODE XREF: move_video_line_left_HL+9j
                                        ; move_video_line_left_HL+18j
        bit     7, (hl)                 ; graphic RH byte?
        jr      Z, loc_0_4676           ; no, skip
        ld      a, (hl)                 ; get character from video (RH byte)
        ld      (de), a                 ; display LH byte
        ld      (hl), #0x20 ; ' '       ; space RH byte

loc_0_4676:                             ; CODE XREF: move_video_line_left_HL+10j
        inc     hl
        inc     de
        djnz    loc_0_466E              ; loop thru row
        pop     hl
        ld      de, #0x3F ; '?'
        add     hl, de
        ld      (hl), #0x20 ; ' '       ; display space on end of row
        ret     
; End of function move_video_line_left_HL


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


add_10_to_score:                        ; CODE XREF: update_score_and_chk_bonus_lifep
        push    hl
        push    bc
        ld      hl, #video_ram+0x3CC    ; tens digit
        call    add_1_to_score_digit
        jr      NZ, loc_0_46A1          ; skip if no carry
        dec     hl                      ; hundreds digit
        call    add_1_to_score_digit
        jr      NZ, loc_0_46A1          ; skip if no carry
        dec     hl                      ; thousands digit
        call    add_1_to_score_digit
        jr      NZ, loc_0_46A1          ; skip if no carry
        dec     hl                      ; tens of thousands digit
        call    add_1_to_score_digit
        jr      NZ, loc_0_46A1          ; skip if no carry
        call    zero_score

loc_0_46A1:                             ; CODE XREF: add_10_to_score+8j
                                        ; add_10_to_score+Ej ...
        pop     bc
        pop     hl
        ret     
; End of function add_10_to_score


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


add_1_to_score_digit:                   ; CODE XREF: add_10_to_score+5p
                                        ; add_10_to_score+Bp ...
        ld      a, (hl)                 ; get score digit
        cp      #0x39 ; '9'             ; 9?
        jr      Z, flag_carry           ; yes, skip
        inc     a                       ; add 1
        ld      (hl), a                 ; store
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

flag_carry:                             ; CODE XREF: add_1_to_score_digit+3j
        ld      (hl), #0x30 ; '0'       ; set to 0
        xor     a                       ; flag carry
        ret     
; End of function add_1_to_score_digit


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


zero_score:                             ; CODE XREF: add_10_to_score+1Cp
                                        ; code:49EFp
        ld      hl, #video_ram+0x3C9    ; score
        ld      b, #5                   ; 5 digits to zap

loc_0_46B5:                             ; CODE XREF: zero_score+8j
        ld      (hl), #0x30 ; '0'       ; set digit to 0
        inc     hl                      ; next digit
        djnz    loc_0_46B5              ; loop thru all score digits
        ret     
; End of function zero_score


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


update_score_and_chk_bonus_life:        ; CODE XREF: update_score_and_chk_bonus_life+27j
                                        ; update_bullet+50p ...
        call    add_10_to_score
        ld      hl, #video_ram+0x3CC    ; tens digit of score
        ld      a, (hl)                 ; get digit
        cp      #0x30 ; '0'             ; 0?
        jr      NZ, loc_0_46E2          ; no, exit
        dec     hl                      ; hundreds digit
        ld      a, (hl)                 ; get digit
        cp      #0x35 ; '5'             ; 5?
        jr      NZ, loc_0_46E2          ; no, skip
        dec     hl                      ; thousands digit
        ld      a, (hl)                 ; get digit
        cp      #0x31 ; '1'             ; 1?
        jr      NZ, loc_0_46E2          ; no, skip
        dec     hl                      ; tens of thousands digit
        ld      a, (hl)                 ; get digit
        cp      #0x30 ; '0'             ; 0?
        jr      NZ, loc_0_46E2          ; no, skip
        ld      a, (no_lives)
        inc     a                       ; bonus life
        ld      (no_lives), a
        call    display_lives_left

loc_0_46E2:                             ; CODE XREF: update_score_and_chk_bonus_life+9j
                                        ; update_score_and_chk_bonus_life+Fj ...
        djnz    update_score_and_chk_bonus_life
        ret     
; End of function update_score_and_chk_bonus_life


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


handle_fire:                            ; CODE XREF: code:4F23p
        ld      a, (bullet_active)
        or      a                       ; already fired?
        ret     NZ                      ; yes, return
        ld      a, (fire_throttle)
        or      a                       ; waiting for throttle?
        ret     NZ                      ; yes, return
        ld      a, #20                  ; init throttle value
        ld      (fire_throttle), a
        ld      a, (ufo_active)
        or      a                       ; on-screen?
        jr      NZ, loc_0_4702          ; yes, skip
        ld      a, (ufo_dir)
        xor     #1                      ; toggle direction
        ld      (ufo_dir), a

loc_0_4702:                             ; CODE XREF: handle_fire+13j
        ld      a, #1
        ld      (bullet_active), a      ; flag fired
        exx     
        ld      hl, (base_centre)
        ld      de, #0xFFC0             ; -64
        add     hl, de                  ; video address of row above
        ld      (bullet_addr), hl       ; save
        ld      a, (hl)                 ; get character from video
        cp      #0x20 ; ' '             ; space?
        jp      NZ, loc_0_4807          ; no, skip
        ld      (hl), #0x5B ; '['       ; display player bullet
        exx     
        ret     
; End of function handle_fire


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


update_bullet:                          ; CODE XREF: update_bullet+ECj
                                        ; code:4F39p
        exx     
        ld      hl, (bullet_addr)
        ld      a, (hl)                 ; get character from video
        cp      #0x5B ; '['             ; player bullet?
        jr      NZ, handle_bullet_hit   ; no, skip
        ld      (hl), #0x20 ; ' '       ; display space
        ld      de, #0xFFC0             ; -64
        add     hl, de                  ; address of row above
        bit     2, h                    ; off the top of the screen?
        jr      Z, delete_bullet        ; yes, skip
        ld      a, (hl)                 ; get character from video
        cp      #0x80 ; '€'             ; graphic space?
        jr      Z, display_bullet       ; yes, skip
        cp      #0x20 ; ' '             ; space?
        jr      NZ, handle_bullet_hit   ; no, skip

display_bullet:                         ; CODE XREF: update_bullet+16j
                                        ; update_bullet+E0j
        ld      (hl), #0x5B ; '['       ; display player bullet

loc_0_473A:                             ; CODE XREF: update_bullet+E8j
        ld      (bullet_addr), hl       ; update bullet address
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_bullet_hit:                      ; CODE XREF: update_bullet+7j
                                        ; update_bullet+1Aj
        ld      de, #video_ram+0x40     ; 2nd line on display
        call    compare_video_addresses
        or      a                       ; bullet in top line now?
        jr      Z, check_and_handle_ufo_hit ; yes, skip
        bit     7, (hl)                 ; graphic character?
        jp      Z, chk_and_handle_bullet_hits_bomb ; no, skip
        push    hl                      ; bullet address
        call    find_end_of_lowest_invader_row
        pop     de                      ; bullet address
        call    compare_video_addresses
        or      a                       ; have we hit an invader?
        push    de                      ; bullet address
        pop     hl                      ; bullet address
        jp      Z, handle_shield_hit    ; no, must be a shield
        call    get_invader_address
        ld      (0x4020), hl            ; set cursor position
        ld      a, (hl)                 ; get character from video
        ld      b, #3                   ; default to 30 pts
        cp      #0xA0 ; ' '             ; 30pt invader character?
        jr      Z, loc_0_476C           ; yes, skip
        jr      C, loc_0_476B           ; 20pt invader character, skip
        dec     b                       ; 10pt invader

loc_0_476B:                             ; CODE XREF: update_bullet+4Cj
        dec     b

loc_0_476C:                             ; CODE XREF: update_bullet+4Aj
        call    update_score_and_chk_bonus_life
        ld      hl, #explosion
        call    display_message
        call    delay_15ms
        ld      hl, #blank_space
        call    display_message
        ld      a, (invaders_left)
        dec     a                       ; end of wave?
        jp      Z, end_of_wave          ; yes, go
        ld      (invaders_left), a
        ld      de, #0
        call    update_invader_row_addresses
        jr      clear_bullet_active
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

delete_bullet:                          ; CODE XREF: update_bullet+11j
        ld      de, #0x40 ; '@'         ; characters/line
        add     hl, de                  ; next row
        ld      (hl), #0x20 ; ' '       ; display space

clear_bullet_active:                    ; CODE XREF: update_bullet+72j
                                        ; update_bullet+82j ...
        xor     a
        ld      (bullet_active), a      ; clear fired flag
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

check_and_handle_ufo_hit:               ; CODE XREF: update_bullet+2Aj
        bit     7, (hl)                 ; graphic character?
        jr      Z, clear_bullet_active  ; no, hit a bomb, exit
        ld      hl, #video_ram
        ld      b, #64                  ; characters/line

loc_0_47A5:                             ; CODE XREF: update_bullet+8Ej
        bit     7, (hl)                 ; graphic character?
        jr      NZ, loc_0_47AC          ; yes, skip
        inc     hl                      ; next video address
        djnz    loc_0_47A5              ; loop thru line

loc_0_47AC:                             ; CODE XREF: update_bullet+8Bj
        push    hl
        ld      hl, #video_ram
        call    clear_video_line_HL     ; wipe UFO
        ld      hl, #6                  ; RAND(1-6)
        call    rand
        ld      b, l                    ; get result
        xor     a                       ; clear carry
        ld      c, #5                   ; 50 pts

loc_0_47BD:                             ; CODE XREF: update_bullet+A2j
        add     a, c                    ; multiplier
        djnz    loc_0_47BD              ; calc ufo score
        ld      b, a
        push    af
        call    update_score_and_chk_bonus_life
        pop     af
        pop     hl
        ld      (0x4020), hl            ; cursor position
        ld      b, #10
        ld      e, a                    ; bonus/10
        ld      hl, #0
        ld      d, l

loc_0_47D1:                             ; CODE XREF: update_bullet+B6j
        add     hl, de
        djnz    loc_0_47D1              ; calc bonus
        ld      a, #0x3C ; '<'
        call    0x33                    ; display character
        call    0xFAF                   ; display integer in HL
        ld      a, #0x3E ; '>'
        call    0x33                    ; display character
        xor     a
        ld      (ufo_active), a         ; flag inactive
        ld      (ufo_timer), a          ; reset timer
        jr      clear_bullet_active
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

chk_and_handle_bullet_hits_bomb:        ; CODE XREF: update_bullet+2Ej
        push    hl
        ld      hl, #3                  ; RAND(1-3)
        call    rand
        ld      a, l                    ; get result
        pop     hl
        cp      #3
        push    af
        call    NZ, handle_bullet_destroys_bomb
        pop     af
        cp      #2
        jp      C, display_bullet       ; RAND=1
        jp      NZ, clear_bullet_active ; RAND=3
        ld      (hl), #0x20 ; ' '       ; display space
        jp      loc_0_473A
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4807:                             ; CODE XREF: handle_fire+30j
        exx     
        jp      update_bullet
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_shield_hit:                      ; CODE XREF: update_bullet+3Cj
        call    erode_shield_from_bullet
        jr      clear_bullet_active
; End of function update_bullet


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


erode_shield_from_bomb:                 ; CODE XREF: handle_drop_new_bomb+90j
                                        ; update_bombs+96p
        push    hl
        push    bc
        ld      a, (hl)                 ; get character from video
        ld      c, a
        ld      a, #0xBC ; '¼'
        and     c
        cp      c
        jr      NZ, loc_0_4822
        ld      a, #0xB0 ; '°'
        and     c
        cp      c
        jr      NZ, loc_0_4822
        ld      a, #0x20 ; ' '

loc_0_4822:                             ; CODE XREF: erode_shield_from_bomb+8j
                                        ; erode_shield_from_bomb+Ej
        cp      #0x80 ; '€'
        jr      NZ, loc_0_4828
        ld      a, #0x20 ; ' '

loc_0_4828:                             ; CODE XREF: erode_shield_from_bomb+14j
        ld      (hl), a                 ; update character
        pop     bc
        pop     hl
        jp      dec_bomb_count
; End of function erode_shield_from_bomb


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


erode_shield_from_bullet:               ; CODE XREF: update_bullet+EFp
        push    hl                      ; bullet address
        push    bc
        ld      a, (hl)                 ; get character from video
        ld      c, a
        ld      a, #0x8F ; ''          ; top 4 cells?
        and     c
        cp      c                       ; match?
        jr      NZ, loc_0_4840          ; no, skip
        ld      a, #0x83 ; 'ƒ'          ; top 2 cells?
        and     c
        cp      c                       ; match?
        jr      NZ, loc_0_4840          ; no, skip
        ld      a, #0x20 ; ' '

loc_0_4840:                             ; CODE XREF: erode_shield_from_bullet+8j
                                        ; erode_shield_from_bullet+Ej
        cp      #0x80 ; '€'             ; blank graphic?
        jr      NZ, loc_0_4846          ; no, skip
        ld      a, #0x20 ; ' '

loc_0_4846:                             ; CODE XREF: erode_shield_from_bullet+14j
        ld      (hl), a                 ; update character
        pop     bc
        pop     hl
        ret     
; End of function erode_shield_from_bullet


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


find_end_of_lowest_invader_row:         ; CODE XREF: update_bullet+32p
                                        ; update_bombs+7Dp
        ld      hl, (row_4_invader_addr)
        ld      a, h
        or      a                       ; any invaders left in row?
        jr      NZ, loc_0_4862          ; yes, continue
        ld      hl, (row_3_invader_addr)
        ld      a, h
        or      a                       ; any invaders left in row?
        jr      NZ, loc_0_4862          ; yes, continue
        ld      hl, (row_2_invader_addr)
        ld      a, h
        or      a                       ; any invaders left in row?
        jr      NZ, loc_0_4862          ; yes, continue
        ld      hl, (row_1_invader_addr)

loc_0_4862:                             ; CODE XREF: find_end_of_lowest_invader_row+5j
                                        ; find_end_of_lowest_invader_row+Cj ...
        push    de
        push    bc
        ld      de, #63                 ; characters/line-1
        add     hl, de                  ; start at end of line
        ld      b, #63                  ; characters/line-1

loc_0_486A:                             ; CODE XREF: find_end_of_lowest_invader_row+25j
        bit     7, (hl)                 ; graphic character?
        jr      NZ, loc_0_4871          ; yes, return
        dec     hl                      ; previous video address
        djnz    loc_0_486A              ; loop thru line

loc_0_4871:                             ; CODE XREF: find_end_of_lowest_invader_row+22j
        pop     bc
        pop     de
        ret     
; End of function find_end_of_lowest_invader_row

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

end_of_wave:                            ; CODE XREF: update_bullet+66j
        jp      new_wave

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


check_for_graphic_in_column:            ; CODE XREF: animate_and_move_invaders+Cp
                                        ; code:4B8Bp
        ld      de, #64                 ; characters/line
        ld      b, #13

loc_0_487C:                             ; CODE XREF: check_for_graphic_in_column+Aj
        bit     7, (hl)                 ; graphic character?
        jr      NZ, loc_0_4886          ; yes, skip
        add     hl, de                  ; next line
        djnz    loc_0_487C              ; loop thru 13 lines
        ld      a, #0x20 ; ' '          ; flag no match
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4886:                             ; CODE XREF: check_for_graphic_in_column+7j
        xor     a                       ; flag match
        ret     
; End of function check_for_graphic_in_column


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


check_and_handle_move:                  ; CODE XREF: code:4F2Bp
        ld      a, (0x3808)             ; keyboard
        and     #5                      ; "X" or "Z" pressed?
        ret     Z                       ; no return
        cp      #4                      ; "Z"?
        jr      NC, handle_move_left    ; yes, skip
        ld      a, (video_ram+0x3BB)    ; right-most position for base
        bit     7, a                    ; graphic character?
        ret     NZ                      ; yes, return (can't move right)
        exx     
        ld      hl, #video_ram+0x380    ; base row
        call    move_video_line_right_HL
        ld      hl, (base_centre)
        inc     hl                      ; move player right
        ld      (base_centre), hl

loc_0_48A6:                             ; CODE XREF: check_and_handle_move+35j
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_move_left:                       ; CODE XREF: check_and_handle_move+8j
        ret     NZ
        ld      a, (video_ram+0x384)    ; left-most position for base
        bit     7, a                    ; graphic character?
        ret     NZ                      ; yes, return (can't move left)
        exx     
        ld      hl, #video_ram+0x380    ; base row
        call    move_video_line_left_HL
        ld      hl, (base_centre)
        dec     hl                      ; move player left
        ld      (base_centre), hl
        jr      loc_0_48A6
; End of function check_and_handle_move


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


check_and_start_ufo:                    ; CODE XREF: code:4F44p
        ld      a, (ufo_timer)
        inc     a                       ; increment_timer
        ld      (ufo_timer), a
        ret     NZ                      ; not time for ufo yet
        ld      a, (invaders_left)
        cp      #8                      ; less than 8 invaders remaining?
        ret     C                       ; yes, return
        ld      a, (ufo_active)
        or      a                       ; on-screen?
        ret     NZ                      ; yes, return
        exx     
        ld      a, #65
        ld      (ufo_TTL), a
        ld      a, (ufo_dir)
        or      a                       ; left?
        jr      Z, loc_0_48E3           ; yes, skip
        ld      hl, #video_ram          ; start on left
        jr      loc_0_48E6
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_48E3:                             ; CODE XREF: check_and_start_ufo+1Dj
        ld      hl, #video_ram+0x3A     ; start on right

loc_0_48E6:                             ; CODE XREF: check_and_start_ufo+22j
        ld      (0x4020), hl            ; update cursor position
        ld      hl, #ufo
        call    display_message
        ld      a, #1                   ; flag on-screen
        ld      (ufo_active), a
        exx     
        ret     
; End of function check_and_start_ufo


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


update_ufo:                             ; CODE XREF: code:4F41p
        ld      a, (ufo_active)
        or      a                       ; ufo on-screen?
        ret     Z                       ; no, return
        exx     
        ld      hl, #video_ram
        ld      b, #63                  ; characters/line-1

loc_0_4901:                             ; CODE XREF: update_ufo+15j
        ld      a, (hl)                 ; get character from video
        cp      #0xBB ; '»'
        jr      Z, loc_0_490F           ; yes, alternate
        cp      #0xB7 ; '·'
        jr      Z, loc_0_4913

loc_0_490A:                             ; CODE XREF: update_ufo+1Bj
                                        ; update_ufo+1Fj
        inc     hl                      ; next video address
        djnz    loc_0_4901              ; loop thru line
        jr      move_ufo
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_490F:                             ; CODE XREF: update_ufo+Ej
        ld      (hl), #0xB7 ; '·'       ; display
        jr      loc_0_490A
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4913:                             ; CODE XREF: update_ufo+12j
        ld      (hl), #0xBB ; '»'       ; display
        jr      loc_0_490A
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

move_ufo:                               ; CODE XREF: update_ufo+17j
        ld      a, (ufo_dir)
        or      a                       ; left?
        jr      Z, move_ufo_left        ; yes, skip
        ld      hl, #video_ram
        call    move_video_line_right_HL
        jr      ufo_TTL_tick
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

move_ufo_left:                          ; CODE XREF: update_ufo+25j
        ld      hl, #video_ram
        call    move_video_line_left_HL

ufo_TTL_tick:                           ; CODE XREF: update_ufo+2Dj
        ld      a, (ufo_TTL)
        dec     a                       ; ufo still active?
        ld      (ufo_TTL), a
        jr      Z, flag_ufo_inactive    ; no, skip

loc_0_4934:                             ; CODE XREF: update_ufo+44j
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

flag_ufo_inactive:                      ; CODE XREF: update_ufo+3Cj
        xor     a                       ; flag ufo inactive
        ld      (ufo_active), a
        jr      loc_0_4934
; End of function update_ufo

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

game_over:                              ; CODE XREF: code:4AB4j code:4B45j
        ld      sp, #0x428A
        ld      hl, #video_ram+0x19     ; cursor position
        ld      (0x4020), hl
        ld      hl, #video_ram          ; start of video
        call    clear_video_line_HL
        ld      hl, #aGAMEOVER          ; "G A M E - O V E R"
        call    display_message_slowly
        call    check_for_new_high_score
        ld      bc, #65535              ; ~1s
        call    0x60                    ; delay
        call    0x60                    ; delay
        call    0x60                    ; delay
        jp      attract_loop

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


display_invader_row:                    ; CODE XREF: code:4A78p code:4A81p ...
        push    hl
        push    de
        push    bc
        ld      b, #10                  ; 10 invaders/row
        push    de
        ld      de, #64
        sbc     hl, de                  ; line above
        pop     de
        inc     hl

loc_0_4970:                             ; CODE XREF: display_invader_row+1Cj
        ld      (0x4020), hl            ; cursor position
        push    de
        push    hl
        ex      de, hl
        call    display_message
        pop     hl
        ld      de, #6                  ; offset to next invader
        add     hl, de                  ; update video address
        pop     de
        djnz    loc_0_4970              ; loop thru 10 invaders
        pop     bc
        pop     de
        pop     hl
        ret     
; End of function display_invader_row


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


update_invader_row_addresses:           ; CODE XREF: update_bullet+6Fp
        push    hl
        push    de
        push    bc
        ld      hl, (row_1_invader_addr)
        call    find_1st_invader_on_row
        ld      (row_1_invader_addr), hl
        ld      hl, (row_2_invader_addr)
        call    find_1st_invader_on_row
        ld      (row_2_invader_addr), hl
        ld      hl, (row_3_invader_addr)
        call    find_1st_invader_on_row
        ld      (row_3_invader_addr), hl
        ld      hl, (row_4_invader_addr)
        call    find_1st_invader_on_row
        ld      (row_4_invader_addr), hl
        pop     bc
        pop     de
        pop     hl
        ret     
; End of function update_invader_row_addresses


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


find_1st_invader_on_row:                ; CODE XREF: update_invader_row_addresses+6p
                                        ; update_invader_row_addresses+Fp ...
        push    hl                      ; invader row address
        ld      b, #63                  ; characters/line-1

loc_0_49B3:                             ; CODE XREF: find_1st_invader_on_row+9j
        ld      a, (hl)                 ; get character from video
        bit     7, a                    ; graphic?
        inc     hl                      ; next video address
        jr      NZ, loc_0_49BF          ; yes, skip
        djnz    loc_0_49B3              ; find 1st invader on row
        pop     hl
        ld      h, #0                   ; flag no invaders on row
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_49BF:                             ; CODE XREF: find_1st_invader_on_row+7j
        pop     hl                      ; invader row address
        add     hl, de                  ; ???
        ret     
; End of function find_1st_invader_on_row

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

start_game:                             ; CODE XREF: check_for_R_key+5j
        xor     a
        ld      (ufo_timer), a
        ld      (unused_4315), a
        ld      (unused_4312), a
        ld      (ufo_dir), a
        ld      (wave_no), a
        ld      (ufo_active), a
        ld      (bullet_active), a
        ld      (keybd_state), a
        inc     a
        ld      (invader_dir), a
        ld      a, #5
        ld      (ufo_timer), a
        ld      a, #3
        ld      (no_lives), a
        call    display_lives_left
        ld      sp, #0x428A
        call    zero_score
        call    display_GOOD_LUCK

new_wave:                               ; CODE XREF: code:4874j
        ld      sp, #0x428A
        xor     a
        ld      (bullet_active), a      ; clear fired flag
        ld      a, (wave_no)
        inc     a                       ; next wave number
        cp      #7                      ; highest?
        jr      NZ, loc_0_4A06          ; no, skip
        ld      a, #1                   ; reset to 1

loc_0_4A06:                             ; CODE XREF: code:4A02j
        ld      (wave_no), a
        and     #6                      ; 2/4/6
        ld      de, #0x40 ; '@'         ; characters/line
        ld      h, d
        ld      l, e                    ; hl=0x0040
        ld      b, #1
        cp      #2                      ; compare wave_no with 2
        jr      C, loc_0_4A1C           ; wave_no=1, skip
        jr      Z, loc_0_4A1A           ; wave_no=2, skip
        inc     b
        add     hl, de

loc_0_4A1A:                             ; CODE XREF: code:4A16j
        inc     b
        add     hl, de

loc_0_4A1C:                             ; CODE XREF: code:4A14j
        ex      de, hl

calc_invader_row_addr:                  ; CODE XREF: code:4A40j
        push    bc
        ld      ix, #init_row_1_invader_addr
        ld      iy, #row_1_invader_addr
        ld      b, #4                   ; 4 rows of invaders

loc_0_4A28:                             ; CODE XREF: code:4A3Dj
        ld      l, 0(ix)
        ld      h, 1(ix)
        add     hl, de                  ; calc video address for invader row
        ld      0(iy), l
        ld      1(iy), h                ; store
        inc     ix
        inc     ix                      ; next row address
        inc     iy
        inc     iy
        djnz    loc_0_4A28              ; loop thru all rows of invaders
        pop     bc
        djnz    calc_invader_row_addr
        call    wipe_screen_left_to_right_slow
        ld      hl, #video_ram+0x309    ; cursor position
        ld      (0x4020), hl
        ld      hl, #shield             ; shield #1
        push    hl
        call    display_message
        ld      hl, #video_ram+0x317    ; cursor position
        ld      (0x4020), hl
        pop     hl
        push    hl                      ; shield #2
        call    display_message
        ld      hl, #video_ram+0x324    ; cursor position
        ld      (0x4020), hl
        pop     hl
        push    hl                      ; shield #3
        call    display_message
        ld      hl, #video_ram+0x331    ; cursor position
        ld      (0x4020), hl
        pop     hl                      ; shield #4
        call    display_message
        ld      de, #invader_30pt
        ld      hl, (row_1_invader_addr)
        call    display_invader_row     ; display 1st row of invaders
        ld      de, #invader_20pt
        ld      hl, (row_2_invader_addr)
        call    display_invader_row     ; display 2nd row of invaders
        ld      de, #invader_10pt
        ld      hl, (row_3_invader_addr)
        call    display_invader_row     ; display 3rd row of invaders
        ld      hl, (row_4_invader_addr)
        call    display_invader_row     ; display 4th row of invaders
        ld      a, #40                  ; number of invaders left
        ld      (invaders_left), a
        ld      (invader_timer), a

init_and_display_player_base:           ; CODE XREF: code:4AD9j
        ld      hl, #video_ram+0x384    ; cursor position
        ld      (0x4020), hl
        ld      hl, #player
        call    display_message         ; draw player base
        ld      hl, #video_ram+0x386
        ld      (base_centre), hl       ; center of base
        jp      init_turn
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

decrement_player_life:                  ; CODE XREF: code:4B2Aj
        ld      a, (no_lives)
        dec     a                       ; any lives left?
        jp      Z, game_over            ; no, exit
        ld      (no_lives), a
        call    display_lives_left
        xor     a
        ld      (bullet_active), a      ; clear fired flag
        ld      (unused_4312), a
        call    restore_space_characters
        ld      hl, #video_ram+0x380
        call    clear_video_line_HL
        ld      bc, #65535              ; ~1s
        call    0x60                    ; delay
        call    0x60                    ; delay
        ld      sp, #0x428A
        jp      init_and_display_player_base

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


invert_display:                         ; CODE XREF: animate_player_hit+4p
                                        ; animate_player_hit+Bj ...
        ld      hl, #video_ram
        ld      bc, #0x400              ; video ram size

loc_0_4AE2:                             ; CODE XREF: invert_display+1Cj
        ld      a, (hl)                 ; get character
        cp      #0x20 ; ' '             ; space?
        jr      NZ, loc_0_4AE9          ; no, skip
        ld      (hl), #0x80 ; '€'       ; graphic space

loc_0_4AE9:                             ; CODE XREF: invert_display+9j
        bit     7, (hl)                 ; graphics character?
        jr      Z, loc_0_4AF4           ; no, skip
        ld      a, (hl)                 ; get character
        cpl                             ; invert
        set     7, a                    ; make graphics character
        res     6, a                    ; 1st block of graphics characters
        ld      (hl), a                 ; display

loc_0_4AF4:                             ; CODE XREF: invert_display+Fj
        inc     hl                      ; next video address
        dec     bc
        ld      a, b
        or      c
        jr      NZ, loc_0_4AE2          ; loop through screen
        ret     
; End of function invert_display


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


get_player_address:                     ; CODE XREF: animate_player_hitp
        ld      hl, (base_centre)
        dec     hl
        dec     hl
        ret     
; End of function get_player_address


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


animate_base_hit:                       ; CODE XREF: animate_player_hit+8p
        ld      a, #0xA6 ; '¦'          ; hash graphic
        ld      b, #0                   ; 256 times

loc_0_4B05:                             ; CODE XREF: animate_base_hit+16j
        push    bc
        push    hl                      ; player base address
        ld      b, #5                   ; 5 chars to display
        xor     #0x3F ; '?'             ; invert hash

loc_0_4B0B:                             ; CODE XREF: animate_base_hit+Cj
        ld      (hl), a                 ; display hash
        inc     hl                      ; next video address
        djnz    loc_0_4B0B              ; loop through 5 chars

loc_0_4B0F:                             ; CODE XREF: animate_base_hit+12j
        ex      (sp), hl
        ex      (sp), hl
        ex      (sp), hl
        ex      (sp), hl                ; delay
        djnz    loc_0_4B0F              ; loop 256 times
        pop     hl
        pop     bc
        djnz    loc_0_4B05              ; loop 256 times
        ret     
; End of function animate_base_hit


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


animate_player_hit:                     ; CODE XREF: code:4B27p
        call    get_player_address
        push    hl
        call    invert_display
        pop     hl
        call    animate_base_hit
        jr      invert_display
; End of function animate_player_hit

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_base_hit:                        ; CODE XREF: update_bombs+93j
        call    animate_player_hit
        jp      decrement_player_life
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

flash_screen_10_times:                  ; CODE XREF: code:4C02j
        ld      b, #10                  ; 10 times

flash_screen:                           ; CODE XREF: code:4B43j
        push    bc
        call    invert_display
        ld      bc, #10000              ; ~140ms
        call    0x60                    ; delay
        call    invert_display
        ld      bc, #10000              ; ~140ms
        call    0x60                    ; delay
        pop     bc
        djnz    flash_screen            ; repeat
        jp      game_over

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


animate_and_move_invaders:              ; CODE XREF: code:4F71p
        push    hl
        push    de
        push    bc
        ld      a, (invader_dir)
        or      a                       ; left?
        jr      Z, animate_and_move_invaders_left ; yes, skip
        ld      hl, #video_ram+0x7F     ; end of 2nd line on screen
        call    check_for_graphic_in_column
        or      a                       ; invaders reached RHS of screen?
        jp      Z, set_invader_dir_left ; yes, skip
        ld      hl, (row_4_invader_addr)
        call    move_invader_row_right
        ld      hl, (row_3_invader_addr)
        call    move_invader_row_right
        ld      hl, (row_2_invader_addr)
        call    move_invader_row_right
        ld      hl, (row_1_invader_addr)
        call    move_invader_row_right
        call    animate_invaders

move_invaders_down_ret:                 ; CODE XREF: code:4BACj code:4C1Dj ...
        pop     bc
        pop     de
        pop     hl
        ret     
; End of function animate_and_move_invaders


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


move_invader_row_right:                 ; CODE XREF: animate_and_move_invaders+16p
                                        ; animate_and_move_invaders+1Cp ...
        ld      a, h
        or      a                       ; any invaders left on this row?
        ret     Z                       ; no, return
        call    move_video_line_right_HL
        ld      de, #64                 ; characters/line
        sbc     hl, de                  ; line above
        jp      move_video_line_right_HL
; End of function move_invader_row_right

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

animate_and_move_invaders_left:         ; CODE XREF: animate_and_move_invaders+7j
        ld      hl, #video_ram+0x40     ; start of 2nd line
        call    check_for_graphic_in_column
        or      a                       ; inavders reached LHS of screen?
        jr      Z, move_invaders_down   ; yes, skip
        call    animate_invaders

move_invaders_left:                     ; CODE XREF: code:4BC6j
        ld      hl, (row_4_invader_addr)
        call    move_invader_row_left
        ld      hl, (row_3_invader_addr)
        call    move_invader_row_left
        ld      hl, (row_2_invader_addr)
        call    move_invader_row_left
        ld      hl, (row_1_invader_addr)
        call    move_invader_row_left
        jr      move_invaders_down_ret

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


move_invader_row_left:                  ; CODE XREF: code:4B97p code:4B9Dp ...
        ld      a, h
        or      a                       ; any invaders left on row?
        ret     Z                       ; no, return
        push    hl
        call    move_video_line_left_HL
        pop     hl
        ld      de, #64                 ; characters/line
        sbc     hl, de                  ; line above
        jp      move_video_line_left_HL
; End of function move_invader_row_left

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

set_invader_dir_left:                   ; CODE XREF: animate_and_move_invaders+10j
        ld      a, (invader_dir)
        xor     #1                      ; toggle invader direction
        ld      (invader_dir), a
        jp      move_invaders_left
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

move_invaders_down:                     ; CODE XREF: code:4B8Fj
        ld      a, (bullet_active)
        or      a                       ; fired?
        jr      Z, loc_0_4BD4           ; no, skip
        ld      hl, (bullet_addr)
        ld      (hl), #0x20 ; ' '       ; display space

loc_0_4BD4:                             ; CODE XREF: code:4BCDj
        ld      ix, #row_4_invader_addr
        ld      b, #4                   ; 4 rows to check

loc_0_4BDA:                             ; CODE XREF: code:4BE9j
        ld      l, 0(ix)
        ld      h, 1(ix)                ; hl = invader addr
        ld      a, h
        or      a                       ; any invaders left on this line?
        call    NZ, move_invader_row_down ; yes, call
        dec     ix
        dec     ix                      ; next invader row address
        djnz    loc_0_4BDA              ; loop thru 4 rows of invaders
        ld      ix, #row_4_invader_addr
        ld      b, #4                   ; 4 rows of invaders
        ld      de, #video_ram+0x380    ; 2nd last line on screen

loc_0_4BF4:                             ; CODE XREF: code:4C0Fj
        ld      l, 0(ix)
        ld      h, 1(ix)                ; HL = invader row addr
        call    get_video_line_below_invaders
        call    compare_video_addresses
        cp      #0x20 ; ' '             ; invaded?
        jp      Z, flash_screen_10_times ; yes, exit
        ld      0(ix), l
        ld      1(ix), h                ; update invader row address
        dec     ix
        dec     ix                      ; row above
        djnz    loc_0_4BF4              ; loop thru 4 rows of invaders
        ld      a, (invader_dir)
        xor     #1                      ; toggler invader direction (=right)
        ld      (invader_dir), a
        ld      a, (bullet_active)
        or      a                       ; fired?
        jp      Z, move_invaders_down_ret ; no, skip
        ld      hl, (bullet_addr)
        ld      a, (hl)                 ; get character from video
        cp      #0x20 ; ' '             ; space?
        jp      NZ, move_invaders_down_ret ; no, skip
        ld      (hl), #0x5B ; '['       ; display player bullet
        jp      move_invaders_down_ret

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


move_invader_row_down:                  ; CODE XREF: code:4BE2p
        push    bc
        push    hl                      ; invader row address
        ld      de, #63                 ; characters/line
        add     hl, de                  ; next line down, 1 character left
        push    hl
        inc     de                      ; 64
        add     hl, de                  ; next line down again
        ex      de, hl                  ; DE = 2 lines below, 1 character left
        pop     hl                      ; invader row+1 address
        ld      b, #128                 ; 2 video lines

loc_0_4C3B:                             ; CODE XREF: move_invader_row_down+1Aj
        ld      a, (de)                 ; get character from video
        cp      #0x80 ; '€'             ; graphic?
        ld      a, (hl)                 ; get character from invader row
        jr      NC, loc_0_4C45          ; yes, ok to overwrite
        cp      #0x80 ; '€'             ; invader a graphic?
        jr      C, loc_0_4C46           ; no, skip

loc_0_4C45:                             ; CODE XREF: move_invader_row_down+11j
        ld      (de), a                 ; move character

loc_0_4C46:                             ; CODE XREF: move_invader_row_down+15j
        dec     de
        dec     hl
        djnz    loc_0_4C3B              ; loop thru 2 lines
        pop     hl
        ld      de, #64                 ; characters/line
        sbc     hl, de                  ; line above
        call    clear_video_line_HL
        pop     bc
        ret     
; End of function move_invader_row_down


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


get_video_line_below_invaders:          ; CODE XREF: code:4BFAp
        ld      a, h
        or      a                       ; any invaders left in row?
        ret     Z                       ; no, return
        push    de
        ld      de, #64                 ; characters/line
        add     hl, de                  ; next line
        pop     de
        ret     
; End of function get_video_line_below_invaders


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


check_for_new_high_score:               ; CODE XREF: code:4951p
        ld      hl, #video_ram+0x3C9    ; score
        ld      de, #video_ram+0x3FA    ; high score
        ld      b, #4                   ; 4 digits to compare

loc_0_4C67:                             ; CODE XREF: check_for_new_high_score+10j
        ld      c, (hl)                 ; get score digit
        ld      a, (de)                 ; get high score digit
        cp      c                       ; score higher?
        jr      C, update_high_score    ; yes, skip
        ret     NZ                      ; done if not the same
        inc     hl
        inc     de                      ; next digits
        djnz    loc_0_4C67              ; loop through all digits
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

update_high_score:                      ; CODE XREF: check_for_new_high_score+Bj
        ld      hl, #video_ram+0x3C9    ; source = score
        ld      de, #video_ram+0x3FA    ; destination = high score
        ld      bc, #5                  ; 5 digits to copy
        ldir                            ; copy
        ret     
; End of function check_for_new_high_score


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


clear_video_line_HL:                    ; CODE XREF: update_bullet+94p
                                        ; code:4948p ...
        push    bc
        push    de
        ld      b, #64                  ; characters/line

loc_0_4C82:                             ; CODE XREF: clear_video_line_HL+7j
        ld      (hl), #0x20 ; ' '       ; display space
        inc     hl                      ; next video address
        djnz    loc_0_4C82              ; clear a line
        pop     de
        pop     bc
        ret     
; End of function clear_video_line_HL


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


handle_drop_new_bomb:                   ; CODE XREF: code:4F65p
        exx     
        ld      b, #4                   ; number of invader rows
        ld      ix, #row_4_invader_addr

loc_0_4C91:                             ; CODE XREF: handle_drop_new_bomb+11j
        ld      a, 1(ix)
        or      a                       ; any invaders left on this row?
        jr      NZ, check_and_handle_new_bomb ; yes, continue
        dec     ix
        dec     ix                      ; next row above
        djnz    loc_0_4C91              ; loop thru all rows

init_bomb_ret:                          ; CODE XREF: handle_drop_new_bomb+3Bj
                                        ; handle_drop_new_bomb+4Ej ...
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

check_and_handle_new_bomb:              ; CODE XREF: handle_drop_new_bomb+Bj
        ld      hl, (base_centre)
        ld      de, #0xC080
        add     hl, de                  ; base X position
        ex      de, hl                  ; base X position
        ld      l, 0(ix)
        ld      h, 1(ix)                ; invader row address
        push    hl
        ld      hl, #3                  ; RAND(1-3)
        call    rand
        ld      a, l                    ; get result
        pop     hl                      ; invader row address
        cp      #1                      ; drop a bomb near the base?
        jr      NZ, random_bomb_x_position ; no, random

loc_0_4CBA:                             ; CODE XREF: handle_drop_new_bomb+84j
        add     hl, de                  ; calc bomb X position
        ld      de, #0xFF80             ; offset of 2 video lines above

loc_0_4CBE:                             ; CODE XREF: handle_drop_new_bomb+39j
        bit     7, (hl)                 ; invader above bomb position?
        jr      NZ, init_new_bomb       ; yes, continue
        add     hl, de                  ; 2 lines above
        djnz    loc_0_4CBE              ; find invader above
        jr      init_bomb_ret           ; no invaders, no bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

init_new_bomb:                          ; CODE XREF: handle_drop_new_bomb+36j
        ld      ix, #bomb_tbl
        ld      b, #4

find_free_bomb_entry:                   ; CODE XREF: handle_drop_new_bomb+4Cj
        ld      a, 1(ix)
        or      a                       ; bomb active?
        jr      Z, loc_0_4CDB           ; no, continue
        call    add_3_to_ix             ; next table location
        djnz    find_free_bomb_entry
        jp      init_bomb_ret           ; no free entries, return
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4CDB:                             ; CODE XREF: handle_drop_new_bomb+47j
        call    get_invader_address
        ld      de, #0x82 ; '‚'         ; 2 lines below and 2 chars right
        add     hl, de                  ; centre under invader
        push    hl
        ld      hl, #3                  ; rand(1-3)
        call    rand
        ld      de, #base_icon+3        ; bomb_characters
        add     hl, de                  ; get random character
        pop     de                      ; centre under invader
        bit     7, e
        jr      Z, check_new_bomb_shield

init_bomb_entry:                        ; CODE XREF: handle_drop_new_bomb+8Aj
        ld      a, (de)                 ; get character from video
        cp      #0x20 ; ' '             ; space?
        jr      NZ, init_bomb_ret       ; no, exit
        ld      a, (hl)                 ; get bomb character from table
        ld      (de), a                 ; display
        ld      0(ix), e
        ld      1(ix), d                ; store bomb address
        ld      2(ix), a                ; store bomb character
        jp      init_bomb_ret
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

random_bomb_x_position:                 ; CODE XREF: handle_drop_new_bomb+2Ej
        push    hl
        ld      hl, #64                 ; RAND(1-64)
        call    rand
        ex      de, hl                  ; DE = result
        pop     hl
        jr      loc_0_4CBA
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

check_new_bomb_shield:                  ; CODE XREF: handle_drop_new_bomb+66j
        ex      de, hl                  ; HL = centre under invader
        bit     7, (hl)                 ; graphic character?
        ex      de, hl
        jr      Z, init_bomb_entry      ; no, continue
        ex      de, hl
        push    hl
        exx     
        pop     hl
        jp      erode_shield_from_bomb
; End of function handle_drop_new_bomb


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


rand:                                   ; CODE XREF: update_bullet+9Ap
                                        ; update_bullet+D2p ...
        push    de
        push    bc
        call    0x14CC                  ; ROM RAND() function
        call    0xA7F                   ; transfer result to HL
        pop     bc
        pop     de
        ret     
; End of function rand


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


get_invader_address:                    ; CODE XREF: update_bullet+3Fp
                                        ; handle_drop_new_bomb+51p
        push    de
        ld      a, (hl)                 ; character at video address
        and     #0x30 ; '0'             ; any pixels on bottom row of cell?
        ld      de, #0xFFC0             ; offset of line above
        jr      NZ, loc_0_4D32          ; yes, skip (top half of invader)
        add     hl, de                  ; line above (top half of invader)

loc_0_4D32:                             ; CODE XREF: get_invader_address+7j
                                        ; get_invader_address+Dj
        bit     7, (hl)                 ; graphic character?
        dec     hl                      ; previous video address
        jr      NZ, loc_0_4D32          ; loop until non-graphic
        inc     hl
        inc     hl                      ; 2nd character of invader
        pop     de
        ret     
; End of function get_invader_address


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


restore_space_characters:               ; CODE XREF: code:4AC4p
        ld      hl, #video_ram
        ld      bc, #0x3C0              ; 15 lines (all but last)

loc_0_4D41:                             ; CODE XREF: restore_space_characters+16j
        bit     7, (hl)                 ; graphics character?
        jr      Z, loc_0_4D4A           ; no, skip
        ld      a, (hl)                 ; get character
        cp      #0x80 ; '€'             ; graphic space character?
        jr      NZ, loc_0_4D4C          ; no, skip

loc_0_4D4A:                             ; CODE XREF: restore_space_characters+8j
        ld      (hl), #0x20 ; ' '       ; convert to space character

loc_0_4D4C:                             ; CODE XREF: restore_space_characters+Dj
        inc     hl                      ; next video address
        dec     bc
        ld      a, b
        or      c                       ; done?
        ret     Z                       ; yes, return
        jr      loc_0_4D41              ; loop through 15 lines
; End of function restore_space_characters


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


delete_bomb:                            ; CODE XREF: update_bombs+20p
                                        ; update_bombs+60p ...
        xor     a                       ; zero bomb address
        ld      1(ix), a

dec_bomb_count:                         ; CODE XREF: erode_shield_from_bomb+1Bj
        ld      a, (unused_4312)
        dec     a                       ; probably supposed to be bomb count
        ld      (unused_4312), a
        ret     
; End of function delete_bomb


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


update_bombs:                           ; CODE XREF: code:4F61p
        exx     
        ld      ix, #bomb_tbl
        ld      b, #4                   ; max 4 bombs

loc_0_4D66:                             ; CODE XREF: update_bombs+10j
        ld      a, 1(ix)
        or      a                       ; valid address?
        jr      NZ, check_and_update_bomb ; yes, skip

next_bomb:                              ; CODE XREF: update_bombs+23j
                                        ; update_bombs+4Bj ...
        call    add_3_to_ix             ; next bomb entry
        djnz    loc_0_4D66              ; loop thru all bombs
        exx     
        ret     
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

check_and_update_bomb:                  ; CODE XREF: update_bombs+Bj
        ld      l, 0(ix)
        ld      h, 1(ix)                ; bomb address
        ld      a, 2(ix)                ; bomb character
        cp      (hl)                    ; same character?
        jr      Z, update_bomb          ; yes, continue
        call    delete_bomb
        jr      next_bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

update_bomb:                            ; CODE XREF: update_bombs+1Ej
        ld      (hl), #0x20 ; ' '       ; display space
        ld      de, #64                 ; characters/line
        add     hl, de                  ; next line down
        ld      0(ix), l
        ld      1(ix), h                ; update bomb address
        push    hl
        ld      de, #video_ram+0x3C0    ; bottom line of video
        call    compare_video_addresses
        or      a                       ; reached bottom of screen?
        push    af
        jr      NZ, delete_bomb_and_loop ; yes, delete bomb
        pop     af
        pop     hl                      ; bomb address
        ld      a, (hl)                 ; get character from video
        cp      #0x5B ; '['             ; player bullet?
        jr      Z, handle_bullet_hit_bomb ; yes, skip
        cp      #0x81 ; ''             ; graphic (non-blank)?
        jr      NC, check_and_handle_bomb_hit ; yes, skip
        ld      a, 2(ix)                ; bomb character
        ld      (hl), a                 ; display
        jr      next_bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_bullet_hit_bomb:                 ; CODE XREF: update_bombs+41j
        push    hl
        push    af
        ld      hl, #3
        call    rand
        ld      a, l
        cp      #2
        jr      C, delete_bomb_and_loop
        jr      NZ, handle_bomb_destroys_bullet
        xor     a
        ld      (bullet_active), a
        call    delete_bomb             ; both destroyed
        pop     af
        pop     hl
        ld      (hl), #0x20 ; ' '
        jr      next_bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

delete_bomb_and_loop:                   ; CODE XREF: update_bombs+3Aj
                                        ; update_bombs+58j ...
        call    delete_bomb
        pop     af
        pop     hl
        jr      next_bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

handle_bomb_destroys_bullet:            ; CODE XREF: update_bombs+5Aj
        xor     a
        ld      (bullet_active), a      ; flag inactive
        pop     af
        pop     hl
        ld      a, 2(ix)                ; bomb character
        ld      (hl), a                 ; display
        jr      next_bomb
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

check_and_handle_bomb_hit:              ; CODE XREF: update_bombs+45j
        ex      de, hl
        call    find_end_of_lowest_invader_row
        call    compare_video_addresses
        ex      de, hl
        push    hl
        push    af
        cp      #0xFF
        jr      Z, delete_bomb_and_loop
        pop     af
        pop     hl
        ld      de, #video_ram+0x380    ; 2nd bottom row
        call    compare_video_addresses
        or      a                       ; possible shield hit?
        jp      NZ, handle_base_hit     ; no, must be player base
        call    erode_shield_from_bomb
        push    hl
        push    af
        jr      delete_bomb_and_loop
; End of function update_bombs


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


zero_bullet_tbl:                        ; CODE XREF: code:4EFBp
        ld      hl, #bomb_tbl
        ld      de, #bomb_tbl+1
        ld      bc, #0xC
        ld      (hl), #0
        ldir    
        ret     
; End of function zero_bullet_tbl


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


handle_bullet_destroys_bomb:            ; CODE XREF: update_bullet+DAp
        push    hl
        exx     
        pop     de
        ld      ix, #bomb_tbl
        ld      b, #4                   ; max bombs

loc_0_4E13:                             ; CODE XREF: handle_bullet_destroys_bomb+1Aj
        ld      l, 0(ix)
        ld      h, 1(ix)                ; bomb address
        call    compare_video_addresses
        cp      #0x20 ; ' '             ; hit?
        jp      Z, loc_0_4E26           ; yes, skip
        call    add_3_to_ix             ; next bullet data
        djnz    loc_0_4E13              ; loop thru all bullets

loc_0_4E26:                             ; CODE XREF: handle_bullet_destroys_bomb+14j
        exx     
        jp      delete_bomb             ; returns
; End of function handle_bullet_destroys_bomb


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


add_3_to_ix:                            ; CODE XREF: handle_drop_new_bomb+49p
                                        ; update_bombs+Dp ...
        inc     ix
        inc     ix
        inc     ix
        ret     
; End of function add_3_to_ix


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


display_GOOD_LUCK:                      ; CODE XREF: code:49F2p
        call    wipe_screen_left_to_right_slow
        ld      hl, #video_ram+0x219    ; cursor position
        ld      b, #50                  ; flash 50 times

loc_0_4E39:                             ; CODE XREF: display_GOOD_LUCK+26j
        push    bc
        ld      (0x4020), hl            ; current cursor position
        push    hl
        ld      hl, #aGoodLuck          ; "GOOD LUCK"
        call    display_message
        call    delay_15ms
        pop     hl                      ; cursor position
        ld      (0x4020), hl
        push    hl
        ld      hl, #blank_x9
        call    display_message
        call    delay_15ms
        pop     hl
        pop     bc
        djnz    loc_0_4E39              ; loop though all flashes
        ret     
; End of function display_GOOD_LUCK


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


delay_15ms:                             ; CODE XREF: update_bullet+59p
                                        ; display_GOOD_LUCK+13p ...
        ld      bc, #1000               ; ~15ms
        jp      0x60                    ; delay
; End of function delay_15ms


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


delay_1_5ms:                            ; CODE XREF: wipe_screen_left_to_right_slow+14p
                                        ; code:4F76p
        ld      bc, #100                ; ~1.5ms
        jp      0x60                    ; delay
; End of function delay_1_5ms


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


print_slow_and_check_for_R_key:         ; CODE XREF: code:4567p code:45A3p ...
        push    hl                      ; ptr message
        pop     ix

loc_0_4E69:                             ; CODE XREF: print_slow_and_check_for_R_key+18j
                                        ; print_slow_and_check_for_R_key+28j
        ld      a, 0(ix)                ; get character
        or      a                       ; done?
        ret     Z                       ; yes, exit
        cp      #9                      ; cursor position embedded?
        jr      NZ, loc_0_4E80          ; no, skip
        ld      l, 1(ix)
        ld      h, 2(ix)                ; cursor position
        ld      (0x4020), hl            ; set ROM variable
        call    add_3_to_ix
        jr      loc_0_4E69              ; next character
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

loc_0_4E80:                             ; CODE XREF: print_slow_and_check_for_R_key+Aj
        call    0x33                    ; display character
        ld      bc, #1280               ; ~20ms
        call    0x60                    ; delay
        call    check_for_R_key
        inc     ix                      ; next character
        jr      loc_0_4E69              ; loop
; End of function print_slow_and_check_for_R_key


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B R O U T I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


display_lives_left:                     ; CODE XREF: update_score_and_chk_bonus_life+24p
                                        ; code:49E9p ...
        push    hl
        push    de
        push    bc
        push    af
        ld      hl, (0x4020)            ; current cursor position
        push    hl
        ld      hl, #video_ram+0x3D0    ; cursor position
        ld      (0x4020), hl
        ld      a, (no_lives)
        dec     a                       ; any lives left?
        jr      Z, wipe_all_ship_icons
        ld      b, a                    ; number of lives

loc_0_4EA5:                             ; CODE XREF: display_lives_left+1Bj
        ld      hl, #base_icon
        call    display_message
        djnz    loc_0_4EA5              ; loop thru all icons
        ld      a, (no_lives)
        ld      b, a
        ld      a, #4
        sub     b                       ; no. icons to wipe
        jr      Z, loc_0_4EC2           ; none, skip
        jr      wipe_ship_icons
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

wipe_all_ship_icons:                    ; CODE XREF: display_lives_left+12j
        ld      b, #3                   ; max 3 ship icons

wipe_ship_icons:                        ; CODE XREF: display_lives_left+26j
                                        ; display_lives_left+30j
        ld      hl, #blank_x3
        call    display_message
        djnz    wipe_ship_icons

loc_0_4EC2:                             ; CODE XREF: display_lives_left+24j
        pop     hl
        ld      (0x4020), hl            ; restore cursor position
        pop     af
        pop     bc
        pop     de
        pop     hl
        ret     
; End of function display_lives_left

; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
blank_x3:.db 0x20, 0x20, 0x20, 0        ; DATA XREF: display_lives_left+2Ao
base_icon:.db 0x88, 0x8E, 0x8C, 0       ; DATA XREF: display_lives_left+15o
                                        ; handle_drop_new_bomb+5Fo
bomb_characters:.db 0x5C ; \            ; bomb characters
        .db 0x56 ; V
        .db 0x2A ; *
aGoodLuck:.ascii 'GOOD LUCK'            ; DATA XREF: display_GOOD_LUCK+Do
        .db 0
blank_x9:.db 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0
                                        ; DATA XREF: display_GOOD_LUCK+1Bo
bomb_tbl:.db 0xD1, 0x3E, 0x56           ; DATA XREF: handle_drop_new_bomb+3Do
                                        ; update_bombs+1o ...
        .db 0xDF, 0, 0x56
        .db 0x92, 0x3F, 0x56
        .db 0, 0, 0
        .db    0 ;  
        .db    0 ;  
        .db    0 ;  
        .db    0 ;  
        .db    0 ;  
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

init_turn:                              ; CODE XREF: code:4AADj
        call    zero_bullet_tbl
        xor     a
        ld      (unused_4312), a
        ld      (game_timer), a

game_loop:                              ; CODE XREF: code:4F95j
        ld      a, (0x3840)             ; read keyboard
        ld      d, a
        ld      bc, #0x200              ; ~7.5ms
        call    0x60                    ; delay
        ld      a, (0x3840)             ; read keyboard
        xor     d
        and     #0x80 ; '€'             ; space - changed state?
        jr      NZ, loc_0_4F26          ; yes, skip
        ld      a, (keybd_state)        ; last read
        ld      e, a
        xor     d                       ; changed state?
        and     d                       ; pressed?
        and     #0x80 ; '€'             ; space only
        ld      a, d
        ld      (keybd_state), a        ; store keyboard state
        call    NZ, handle_fire         ; yes, call

loc_0_4F26:                             ; CODE XREF: code:4F15j
        ld      a, (game_timer)
        and     #3                      ; time to move player?
        call    Z, check_and_handle_move ; yes, call
        ld      a, (bullet_active)
        or      a                       ; fired?
        jr      Z, loc_0_4F3C           ; no, skip
        ld      a, (game_timer)
        and     #3                      ; time to move bullet?
        call    Z, update_bullet        ; yes, call

loc_0_4F3C:                             ; CODE XREF: code:4F32j
        ld      a, (game_timer)
        and     #7                      ; time to move UFO?
        call    Z, update_ufo           ; yes, call
        call    check_and_start_ufo
        ld      a, (ufo_active)
        or      a                       ; on-screen?
        jr      NZ, loc_0_4F5A          ; yes, skip
        ld      a, (ufo_timer)
        cp      #0x80 ; '€'             ; time to wipe bonus?
        jr      NZ, loc_0_4F5A          ; no, skip
        ld      hl, #video_ram
        call    clear_video_line_HL     ; wipe bonus

loc_0_4F5A:                             ; CODE XREF: code:4F4Bj code:4F52j
        nop     
        ld      a, (game_timer)
        and     #0xF                    ; time to update bombs?
        push    af
        call    Z, update_bombs         ; yes, call
        pop     af
        call    Z, handle_drop_new_bomb
        ld      hl, #game_timer
        inc     (hl)                    ; increment game timer
        ld      a, (invader_timer)
        dec     a                       ; tick
        push    af                      ; time to move invaders?
        call    Z, animate_and_move_invaders ; yes, call
        pop     af
        push    af
        call    NZ, delay_1_5ms
        pop     af                      ; invader timer expired?
        jr      NZ, loc_0_4F82          ; no, skip
        ld      a, (invaders_left)
        add     a, a
        sub     #1                      ; calc new invader timer

loc_0_4F82:                             ; CODE XREF: code:4F7Aj
        ld      (invader_timer), a
        ld      a, (bullet_active)
        or      a                       ; fired?
        jr      NZ, loc_0_4F95          ; yes, skip
        ld      a, (fire_throttle)
        or      a
        jr      Z, loc_0_4F95
        dec     a
        ld      (fire_throttle), a

loc_0_4F95:                             ; CODE XREF: code:4F89j code:4F8Fj
        jp      game_loop
; ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
aCopyrightC1979:.ascii 'COPYRIGHT (C) 1979, '
        .db 0xB0, 0x37, 0x2F, 0x31, 0x33, 0x42, 0x59, 0x20, 0x54, 0x52
        .db 0x53, 0x2D, 0x42, 0x4D, 0x20, 0x4B, 0x4F, 0x47, 0x41, 0x4E
        .db 0x45, 0x49, 0, 0x81, 0x5F, 0x7A, 0xFE, 0x30, 0x28, 2, 0x77
        .db 0x23, 0x7B, 0xE, 0xA, 0x10, 0xEC, 0xC6, 0x30, 0x77, 0x23, 0x36
        .db 3, 0xE1, 6, 0x20, 0x3E, 0, 0x3D, 0x20, 4, 0x77, 0x23, 0x10
        .db 0xFC, 0xAF, 0xC9, 0x3A, 0xC4, 0x4E, 0x6F, 0xCB, 0xA6, 0x5A
        .db 0x23, 0x56, 0xCD, 0x82, 0x4E, 0x7B, 0xF, 0xF, 0xF, 0xE6, 0x1F
        .db 0xC5, 0x21, 0xC0, 0x4D, 0x4F, 6, 0, 9, 0x7B
; end of 'code'

; end of file
