# TCL File Generated by Component Editor 8.1
# Tue Apr 14 12:56:21 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_atahost_top "avalon_atahost_top" v1.0
# | null 2009.04.14.12:56:21
# | 
# | 
# | E:/markm/pace/pacedev.net/sw/src/platform/coco3-becker/lpc_emu/ip/ocide3/avalon_atahost_top.vhd
# | 
# |    ./ATAHOST_CONTROLLER.vhd syn, sim
# |    ./ATAHOST_DMA.vhd syn, sim
# |    ./ATAHOST_FIFO_RX.vhd syn, sim
# |    ./ATAHOST_FIFO_TX.vhd syn, sim
# |    ./atahost_pio_actrl.vhd syn, sim
# |    ./atahost_pio_controller.vhd syn, sim
# |    ./atahost_pio_tctrl.vhd syn, sim
# |    ./atahost_reg_buf.vhd syn, sim
# |    ./atahost_top.vhd syn, sim
# |    ./atahost_wb_slave.vhd syn, sim
# |    ./avalon_atahost_top.vhd syn, sim
# |    ./ro_cnt.vhd syn, sim
# |    ./ud_cnt.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module avalon_atahost_top
# | 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_atahost_top
set_module_property VERSION 1.0
set_module_property GROUP PACE
set_module_property DISPLAY_NAME avalon_atahost_top
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE avalon_atahost_top.vhd
set_module_property TOP_LEVEL_HDL_MODULE AVALON_ATAHOST_TOP
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ATAHOST_CONTROLLER.vhd {SYNTHESIS SIMULATION}
add_file ATAHOST_DMA.vhd {SYNTHESIS SIMULATION}
add_file ATAHOST_FIFO_RX.vhd {SYNTHESIS SIMULATION}
add_file ATAHOST_FIFO_TX.vhd {SYNTHESIS SIMULATION}
add_file atahost_pio_actrl.vhd {SYNTHESIS SIMULATION}
add_file atahost_pio_controller.vhd {SYNTHESIS SIMULATION}
add_file atahost_pio_tctrl.vhd {SYNTHESIS SIMULATION}
add_file atahost_reg_buf.vhd {SYNTHESIS SIMULATION}
add_file atahost_top.vhd {SYNTHESIS SIMULATION}
add_file atahost_wb_slave.vhd {SYNTHESIS SIMULATION}
add_file avalon_atahost_top.vhd {SYNTHESIS SIMULATION}
add_file ro_cnt.vhd {SYNTHESIS SIMULATION}
add_file ud_cnt.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter TWIDTH NATURAL 8
set_parameter_property TWIDTH DISPLAY_NAME TWIDTH
set_parameter_property TWIDTH UNITS None
set_parameter_property TWIDTH AFFECTS_PORT_WIDTHS true
add_parameter PIO_mode0_T1 NATURAL 6
set_parameter_property PIO_mode0_T1 DISPLAY_NAME PIO_mode0_T1
set_parameter_property PIO_mode0_T1 UNITS None
set_parameter_property PIO_mode0_T1 AFFECTS_PORT_WIDTHS true
add_parameter PIO_mode0_T2 NATURAL 28
set_parameter_property PIO_mode0_T2 DISPLAY_NAME PIO_mode0_T2
set_parameter_property PIO_mode0_T2 UNITS None
set_parameter_property PIO_mode0_T2 AFFECTS_PORT_WIDTHS true
add_parameter PIO_mode0_T4 NATURAL 2
set_parameter_property PIO_mode0_T4 DISPLAY_NAME PIO_mode0_T4
set_parameter_property PIO_mode0_T4 UNITS None
set_parameter_property PIO_mode0_T4 AFFECTS_PORT_WIDTHS true
add_parameter PIO_mode0_Teoc NATURAL 23
set_parameter_property PIO_mode0_Teoc DISPLAY_NAME PIO_mode0_Teoc
set_parameter_property PIO_mode0_Teoc UNITS None
set_parameter_property PIO_mode0_Teoc AFFECTS_PORT_WIDTHS true
add_parameter DMA_mode0_Tm NATURAL 0
set_parameter_property DMA_mode0_Tm DISPLAY_NAME DMA_mode0_Tm
set_parameter_property DMA_mode0_Tm UNITS None
set_parameter_property DMA_mode0_Tm AFFECTS_PORT_WIDTHS true
add_parameter DMA_mode0_Td NATURAL 10
set_parameter_property DMA_mode0_Td DISPLAY_NAME DMA_mode0_Td
set_parameter_property DMA_mode0_Td UNITS None
set_parameter_property DMA_mode0_Td AFFECTS_PORT_WIDTHS true
add_parameter DMA_mode0_Teoc NATURAL 12
set_parameter_property DMA_mode0_Teoc DISPLAY_NAME DMA_mode0_Teoc
set_parameter_property DMA_mode0_Teoc UNITS None
set_parameter_property DMA_mode0_Teoc AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end
set_interface_property clockreset ptfSchematicName ""

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_0
# | 
add_interface conduit_end_0 conduit end

add_interface_port conduit_end_0 coe_arst_arst export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressSpan 128
set_interface_property s1 bridgesToMaster ""
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 minimumUninterruptedRunLength 1
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clockreset

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_waitrequest_n waitrequest_n Output 1
add_interface_port s1 avs_s1_address address Input 5
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq1
# | 
add_interface irq1 interrupt end
set_interface_property irq1 associatedAddressablePoint s1

set_interface_property irq1 ASSOCIATED_CLOCK clockreset

add_interface_port irq1 ins_irq1_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s2
# | 
add_interface s2 avalon end
set_interface_property s2 addressAlignment DYNAMIC
set_interface_property s2 addressSpan 4
set_interface_property s2 bridgesToMaster ""
set_interface_property s2 burstOnBurstBoundariesOnly false
set_interface_property s2 holdTime 0
set_interface_property s2 isMemoryDevice false
set_interface_property s2 isNonVolatileStorage false
set_interface_property s2 linewrapBursts false
set_interface_property s2 maximumPendingReadTransactions 0
set_interface_property s2 minimumUninterruptedRunLength 1
set_interface_property s2 printableDevice false
set_interface_property s2 readLatency 0
set_interface_property s2 readWaitTime 1
set_interface_property s2 setupTime 0
set_interface_property s2 timingUnits Cycles
set_interface_property s2 writeWaitTime 0

set_interface_property s2 ASSOCIATED_CLOCK clockreset

add_interface_port s2 avs_s2_chipselect chipselect Input 1
add_interface_port s2 avs_s2_waitrequest_n waitrequest_n Output 1
add_interface_port s2 avs_s2_writedata writedata Input 32
add_interface_port s2 avs_s2_readdata readdata Output 32
add_interface_port s2 avs_s2_byteenable byteenable Input 4
add_interface_port s2 avs_s2_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_1
# | 
add_interface conduit_end_1 conduit end

add_interface_port conduit_end_1 coe_dma_req export Output 1
add_interface_port conduit_end_1 coe_dma_done export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_2
# | 
add_interface conduit_end_2 conduit end

add_interface_port conduit_end_2 coe_ata_resetn export Output 1
add_interface_port conduit_end_2 coe_ata_dd_i export Input 16
add_interface_port conduit_end_2 coe_ata_dd_o export Output 16
add_interface_port conduit_end_2 coe_ata_dd_oe export Output 1
add_interface_port conduit_end_2 coe_ata_da export Output 3
add_interface_port conduit_end_2 coe_ata_cs0n export Output 1
add_interface_port conduit_end_2 coe_ata_cs1n export Output 1
add_interface_port conduit_end_2 coe_ata_diorn export Output 1
add_interface_port conduit_end_2 coe_ata_diown export Output 1
add_interface_port conduit_end_2 coe_ata_iordy export Input 1
add_interface_port conduit_end_2 coe_ata_intrq export Input 1
add_interface_port conduit_end_2 coe_ata_dmarq export Input 1
add_interface_port conduit_end_2 coe_ata_dmackn export Output 1
# | 
# +-----------------------------------
